name: ClassicPress Coding Standards (CPCS)

on: [pull_request, push]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    phpcs:
        name: CPCS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  tools: composer

            - name: Install PHPCS + WPCS
              run: |
                  composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

                  composer global require squizlabs/php_codesniffer:^3.13
                  composer global require dealerdirect/phpcodesniffer-composer-installer
                  composer global require wp-coding-standards/wpcs:^2.3

                  echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

            - name: Get CPCS ruleset
              run: |
                  wget -O phpcs.xml https://raw.githubusercontent.com/ClassicPress/ClassicPress-Coding-Standards/main/phpcs.xml

                  sed -i '/^\t<!-- start config -->.*/a\
                    <file>.</file>
                    ' phpcs.xml

                  sed -i '/MY_DOMAIN/ s//fx-shortcodes/' phpcs.xml

                  # Add PHP 8 support
                  sed -i 's|</ruleset>|    <config name="testVersion" value="8.0-"/>\n</ruleset>|' phpcs.xml

                  cp phpcs.xml phpcs.xml.dist

            - name: Verify install
              run: phpcs -i

            - name: Run PHPCS
              run: phpcs --standard=phpcs.xml.dist --report-full --report-summary
